config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :games do
    resources :ruby_objects
  end

  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

# Here are the validations and other things related with the Game model
class Game < ApplicationRecord
  has_many :ruby_objects, dependent: :destroy
  validates :name, :rival, presence: true, length: { in: 3..25 }
  validate :different_names

  def different_names
    errors.add(:rival, "can't have the same name as player one") if name == rival
    throw(:abort)
  end
end

app/models/player.rb
class Player < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/ruby_object.rb
# frozen_string_literal: true

# Here are the validations and other things related with the RubyObject model
class RubyObject < ApplicationRecord
  belongs_to :game

  validates :number_attributes, numericality: { only_integer: true,
                                                greater_than_or_equal_to: 1,
                                                less_than_or_equal_to: 25 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# Here are the CRUD methods to the Games
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to games_path
    else
      render 'new'
    end
  end

  def destroy
    @games = Game.find(params[:id])
    @games.destroy

    redirect_to game_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :rival)
  end
end

app/controllers/ruby_objects_controller.rb
# frozen_string_literal: true

# Here are the CRUD's methods to the RubyObject
class RubyObjectsController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @ruby_object = @game.ruby_objects.create(ruby_object_params)
    update_data(@game, @ruby_object)
    redirect_to game_path(@game)
  end

  private

  def ruby_object_params
    params.require(:ruby_object).permit(:attacker, :number_attributes)
  end

  def update_data(game, ruby_object)
    if game.turn == 1
      new_points = game.hit_points_rival - ruby_object.number_attributes
      game.update(hit_points_rival: new_points, turn: 2)
    else
      new_points = game.hit_points - ruby_object.number_attributes
      game.update(hit_points: new_points, turn: 1)
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Welcome controller
class WelcomeController < ApplicationController
  def index
    @game = Game.new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Here are the helpers application
module ApplicationHelper
end

app/helpers/games_helper.rb
# frozen_string_literal: true

# Here are the Games Helper
module GamesHelper
  def number_attributes
    rand(1..5) + value_to_sum
  end

  def value_to_sum
    num = rand(1..100)
    case num
    when 1..20 then 2
    when 21..30 then 5
    when 31..35 then 10
    when 36 then 20
    when 37..100 then 0
    end
  end

  def winner_health(game)
    if game.hit_points > game.hit_points_rival
      game.hit_points
    else
      game.hit_points_rival
    end
  end

  def winner(game)
    if game.hit_points > game.hit_points_rival
      game.name
    else
      game.rival
    end
  end

  def show_object_generator(game)
    if game.hit_points <= 0
      "#{game.rival} is the winner."
    elsif game.hit_points_rival <= 0
      "#{game.name} is the winner."
    else
      render 'ruby_objects/generator'
    end
  end
end

app/helpers/ruby_objects_helper.rb
# frozen_string_literal: true

# Here are the RubyObjects helpers
module RubyObjectsHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

# Here are the Welcome Helper
module WelcomeHelper
end

app/views/games/_form.html.erb
<div class="container w-50">
  <%= form_with model: @game, local: true do |form| %>

    <% if @game.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@game.errors.count, "error") %> prohibited
          this game from being saved:
        </h2>
        <ul>
          <% @game.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class='form-group'>
      <%= form.label :player_one %>
      <%= form.text_field :name, required: true, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= form.label :player_two %>
      <%= form.text_field :rival, required: true, class: 'form-control' %>
    </div>
    
    <%= form.submit 'Go to play', class: 'btn btn-primary' %>

  <% end %>
  <br>
  <%= link_to 'Go to games', games_path, class: 'btn btn-secondary btn-sm' %>
</div>

app/views/games/_new.html.erb
<%= form_with model: @game, local: true do |form| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this game from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :player_one %>
    <%= form.text_field :name, required: true %>
  </p>

  <p>
    <%= form.label :player_two %>
    <%= form.text_field :rival, required: true %>
  </p>
  
  <%= form.submit 'Go to play' %>

<% end %>

app/views/games/index.html.erb
<h1>Ranking Games</h1>

<table class='table table-striped table-sm w-75'>
  <thead>
    <tr>
      <th>Player 1 Name</th>
      <th>Player 2 Name</th>
      <th>Winner Wall Health Remaining</th>
      <th>Winner</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.rival %></td>
        <td><%= winner_health(game) %></td>
        <td><%= winner(game) %></td>
        <td><%= link_to 'Go', game_path(game), class: 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Delete', game_path(game), class: 'btn btn-danger btn-sm',
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Game', new_game_path, class: 'btn btn-primary' %>

app/views/games/new.html.erb
<h1>Names of players to start playing</h1><br>

<%= render 'form' %>

app/views/games/show.html.erb
<h1>Game</h1>

<table class='table w-75'>
  <thead>
    <tr>
      <th>Scores</th>
      <th>Attribute numbers of the five last objects history</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <p>
          <strong>Player 1:</strong>
          <%= @game.name %>
          <% if @game.turn == 1 %>
            <-
          <% end %>
        </p>

        <p>
          <strong>Player 1 hit points:</strong>
          <%= @game.hit_points %>
        </p>

        <p>
          <strong>Player 2:</strong>
          <%= @game.rival %>
          <% if @game.turn == 2 %>
            <-
          <% end %>
        </p>

        <p>
          <strong>Player 2 hit points:</strong>
          <%= @game.hit_points_rival %>
        </p>
      </td>
      <td>
        <table class='table table-striped table-sm'>
          <thead>
            <tr>
              <th>Player one</th>
              <th>Player two</th>
            </tr>
          </thead>
          <tbody>
            <% @game.ruby_objects.last(10).reverse_each do |r_o| %>
              <tr>
                <td><%= r_o.number_attributes if r_o.attacker == 1 %></td>
                <td><%= r_o.number_attributes if r_o.attacker == 2 %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </td>
    </tr>
  </tbody>
</table>

<div>
  <% if show_object_generator(@game).class == String %>
    <h3><%= show_object_generator(@game) %></h3>
    <% else %>
    <%= show_object_generator(@game) %>
  <% end %>
</div>
<br>
<%= link_to 'Back', games_path, class: 'btn btn-secondary btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Objectcannon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/players/new.html.erb
<h1>New Player for Game </h1>

<%= form_with model: @player do |form| %>

  <p>
    <%= form.label :player_one %>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :player_two %>
    <%= form.text_field :rival %>
  </p>

  <%= form.submit 'Go to play' %>
  
<% end %>

app/views/ruby_objects/_generator.html.erb
<h2>Generated object</h2>

<div class="w-25">
  <%= form_with(model: [ @game, @game.ruby_objects.build ], local: true) do |form| %>
    <div class='form-group'>
      <%= form.label :attacker %><br>
      <%= form.text_field :attacker, value: @game.turn, readonly: true, class: 'form-control' %>
    </div>
    <div class='form-group'>
      <%= form.label :number_attributes %><br>
      <%= form.text_field :number_attributes, value: number_attributes, readonly: true, class: 'form-control' %>
    </div>
    <%= form.submit 'Launch Object', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Object Cannon Game</h1><br>

<%= render 'games/form' %>